name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dotAIslash/dotaislash-conformance
      
      - name: Checkout schemas
        uses: actions/checkout@v4
        with:
          repository: dotAIslash/dotaislash-schemas
          path: '../dotaislash-schemas'
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.3.0
      
      - name: Build schemas dependency
        run: |
          cd ../dotaislash-schemas
          bun install
          bun run build
      
      - name: Install dependencies
        run: bun install
      
      - name: Lint
        run: bun run lint
      
      - name: Build
        run: bun run build
      
      - name: Test
        run: bun test
